{{flutter_js}}
{{flutter_build_config}}

(async () => {
  const splash = document.getElementById('splash');
  const showError = (message) => {
    const el = document.getElementById('splash-error');
    el.textContent = message;
    el.style.display = 'block';
  };
  window.addEventListener('flutter-first-frame', () => {
    splash.classList.add('done');
    setTimeout(() => splash.remove(), 300);
  }, { once: true });

  // sw.js is generated by scripts/web/build.sh. A new build installs in the
  // background and waits; it is activated here, before the app loads, so an
  // update applies on the next launch without closing every window first.
  if ('serviceWorker' in navigator && window.isSecureContext) {
    try {
      const registration = await navigator.serviceWorker.register('sw.js', { updateViaCache: 'none' });
      if (registration.waiting && navigator.serviceWorker.controller) {
        await new Promise((resolve) => {
          navigator.serviceWorker.addEventListener('controllerchange', resolve, { once: true });
          registration.waiting.postMessage('skipWaiting');
          setTimeout(resolve, 3000);
        });
        location.reload();
        return;
      }
    } catch (e) {
      console.warn('Service worker registration failed', e);
    }
  }

  try {
    await _flutter.loader.load({
      config: {
        // Skwasm runs single-threaded unless the host sends COOP/COEP headers.
        suppressMultithreadingWarning: true,
      },
    });
  } catch (e) {
    console.error(e);
    showError('Plezy could not start in this browser. It needs a recent Chrome, Edge or Firefox.');
  }
})();
